apiVersion: v1
kind: Deployment
metadata:
  name: clinica-api-deployment
spec:
  selector:
    matchLabels:
      app: clinica-api
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: clinica-api
    spec:
      containers:
      - name: clinica-api
        image: gcr.io/clinica-400119/github.com/dallbia/casagrandeapi
        ports:
        - containerPort: 80
