---
apiVersion: "apps/v1.1"
kind: "Deployment"
metadata:
  name: "clinica-api-deployment"
  namespace: "default"
  labels:
    api: "clinica-api-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      api: "clinica-api-deployment"
  template:
    metadata:
      labels:
        api: "clinica-api-deployment"
    spec:
      containers:
      - name: "clinica-api"
        image: "gcr.io/clinica-400119/github.com/dallbia/casagrandeapi"



apiVersion: apps/v1
kind: Deployment
metadata:  
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:gcb-build-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/version: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              f:gcb-build-id: {}
            f:labels:
              .: {}
              f:app: {}
              f:app.kubernetes.io/version: {}
          f:spec:
            f:containers:
              k:{"name":"clinica-api"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"ASPNETCORE_ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"TZ"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":80,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":443,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-01-09T15:28:26Z"  
  name: clinica-api-deployment
  namespace: default
